# Generated by Django 5.2.3 on 2025-06-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('studentId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('moy1', models.FloatField(max_length=50)),
                ('credit1', models.IntegerField()),
                ('moy2', models.FloatField(max_length=50)),
                ('credit2', models.CharField(max_length=50)),
                ('moy_total', models.FloatField(max_length=50)),
                ('credit_total', models.IntegerField()),
            ],
        ),
    ]
