# Generated by Django 5.2.3 on 2025-06-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='resultat',
            field=models.CharField(default='En attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='credit2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='group',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='moy1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='moy2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='moy_total',
            field=models.FloatField(),
        ),
    ]
